FUNÇÃO DE CONSELHEIRO
INSTRUTOR
DIRETOR

ELES TEM A POSSIBILIDADE ENVIAR REQUISITOS PARA SEREM FEITOS

OS REQUITOS DEVEM APARECER PARA OS DESBRAVADORES EM SEU PERFIL COM DESTAQUE EM LARANJA, E FICAR VERDE QUANDO FOR APROVADO.

VAMOS APLICAR MUITIPLAS FUNCOES E SEPARAR OS NIVEIS DE ACESSO

DIRETOR E SECRETARIOS TEM ACESSO TOTAL
TESOURARIA ACESSOA FINANCEIRO
INSTRUTORES QUANDO ASSOCIADO A ESPECIALIDADE ELES FARAO A ASSOCIAÇÃO DOS MEMBROS NA ESPECIALIDADE E CLASSES.

VAMOS TER A FUNÇÃO DE INSTRUTOR DE DEVERÁ ESTAR ASSOCIADO A UMA CLASSE OU ESPECIALIDADE PARA TER ACESSO

OS CONSELHEIROS TERÃO A LIBERDADE DE LANÇAR E VALIDAR OS REQUISITOS QUANDO PRECISO

TODOS OS REQUISITOS DEVE CONSTAR. APROVADO POR.





SIMPLIFICAR O MENU E REMOVER O QUE TIVER FUNÇÕES SIMILARES TIPO,  DOIS BOTOES BOTOES QUE LEVAM PARA A MESMA FUNCIONALIDADE



NO ACESSO DO MASTER, IMPLEMENTAR E LIBERAR IMPORTAÇÃO VIA URL DOS REQUISITOS CLASSE E ESPECIALIDADES, COM UM POPUP PARA ORGANIZAR OS REQUISITOS OU AGRUPAR
NO CADASTRO DO MASTER, EXIBIR OS CADASTROS DE ASSOCIÇÃO, DISTRITOS E UNIÕES

Talvez avançar para o Financeiro/Seguro, Loja Virtual ou Eventos?)

